### ISSUE TITLE
[BUG] Image upload payload mismatches

### ISSUE THREAD

**Issue by Semanual** [Furnyr/Dissonity#23]
**Describe the bug**
image_url is an empty string, because the payload received by dissonity and the expected payload are mismatching

**Reproduction**
Steps to reproduce the behavior.
1. Call the following code in C#:
```cs
ImageUploadData image = await Api.InitiateImageUpload();
if (image.canceled) {
    return null;
}
Debug.Log(image.image_url);
```
2. Upload an image in a discord activity
3. It prints a blank string

**Expected behavior**
image_url is the string under data.image_url.image_url, not a blank string

**Screenshots**
![imagem](https://github.com/user-attachments/assets/c69a4265-cfff-4f7a-a7b3-d59f4573659d)

**Additional context**
As you can see, the actual URL is inside data.image_url.image_url, but dissonity expects it to be data.image_url. So, C# just parses out an empty string inside image_url.

**Comment by Furnyr** [comment]
Thank you for the report, the image url should be returned correctly in f8ca018dbfc6de4633198278a082aee3c1e594b7, NPM `1.3.2`.
